name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build files
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist
      - name: List build files
        run: ls dist
      - name: Publish to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          debug: true
          source: dist/*
          target: "/var/www/html/homepage/"
